/**
 * Node Builder
 *
 * Converts simplified BlockNode/InlineContent types from AI operations
 * into Tiptap JSONContent format.
 */

import type { JSONContent } from "@tiptap/core";

import type {
  BlockNode,
  InlineContent,
  ListItem,
  MarkType,
} from "@package/ai-agent";

/**
 * Convert a MarkType to Tiptap mark format
 */
function markToJSON(mark: MarkType): { type: string } {
  return { type: mark };
}

/**
 * Convert InlineContent array to Tiptap JSONContent array
 */
export function inlineContentToJSON(content: InlineContent[]): JSONContent[] {
  return content.map((item): JSONContent => {
    switch (item.type) {
      case "text":
        return {
          type: "text",
          text: item.text,
          marks: item.marks?.map(markToJSON),
        };

      case "blank":
        return {
          type: "blank",
          attrs: {
            correctAnswer: item.correctAnswer,
            alternativeAnswers: item.alternativeAnswers ?? [],
            hint: item.hint ?? null,
            // These are managed by the editor, not AI:
            blankIndex: 0, // Will be auto-calculated
            studentAnswer: "", // Student data
          },
        };

      case "hardBreak":
        return { type: "hardBreak" };
    }
  });
}

/**
 * Convert a ListItem to Tiptap listItem JSONContent
 */
function listItemToJSON(item: ListItem): JSONContent {
  return {
    type: "listItem",
    content: item.content.map(blockNodeToJSON),
  };
}

/**
 * Convert a BlockNode to Tiptap JSONContent
 */
export function blockNodeToJSON(block: BlockNode): JSONContent {
  switch (block.type) {
    case "paragraph":
      return {
        type: "paragraph",
        content: block.content ? inlineContentToJSON(block.content) : undefined,
      };

    case "heading":
      return {
        type: "heading",
        attrs: { level: block.level },
        content: block.content ? inlineContentToJSON(block.content) : undefined,
      };

    case "bulletList":
      return {
        type: "bulletList",
        content: block.items.map(listItemToJSON),
      };

    case "orderedList":
      return {
        type: "orderedList",
        content: block.items.map(listItemToJSON),
      };

    case "blockquote":
      return {
        type: "blockquote",
        content: block.content.map(blockNodeToJSON),
      };

    case "horizontalRule":
      return {
        type: "horizontalRule",
      };

    case "exercise":
      return {
        type: "exercise",
        // attrs.id will be generated by UniqueID extension
        // attrs.index will be auto-calculated by Exercise extension
        content: block.content.map(blockNodeToJSON),
      };

    case "group":
      return {
        type: "group",
        content: block.content.map(blockNodeToJSON),
      };

    case "noteBlock":
      return {
        type: "noteBlock",
        content: block.content.map(blockNodeToJSON),
      };

    case "writingArea":
      return {
        type: "writingArea",
        attrs: {
          lines: block.lines ?? 5,
          placeholder: block.placeholder ?? "Write your answer here...",
        },
        // WritingArea needs at least one paragraph for student to write in
        content: [{ type: "paragraph" }],
      };
  }
}

/**
 * Convert an array of BlockNodes to Tiptap JSONContent array
 */
export function blockNodesToJSON(blocks: BlockNode[]): JSONContent[] {
  return blocks.map(blockNodeToJSON);
}
