/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as JoinTokenRouteImport } from './routes/join/$token'
import { Route as ProtectedEditorRouteImport } from './routes/_protected/editor'
import { Route as ProtectedCollabRouteImport } from './routes/_protected/collab'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedTeacherSubscribeRouteImport } from './routes/_protected/teacher/subscribe'
import { Route as ProtectedLessonIdRouteImport } from './routes/_protected/lesson/$id'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedEditorRoute = ProtectedEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCollabRoute = ProtectedCollabRouteImport.update({
  id: '/collab',
  path: '/collab',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTeacherSubscribeRoute =
  ProtectedTeacherSubscribeRouteImport.update({
    id: '/teacher/subscribe',
    path: '/teacher/subscribe',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedLessonIdRoute = ProtectedLessonIdRouteImport.update({
  id: '/lesson/$id',
  path: '/lesson/$id',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/collab': typeof ProtectedCollabRoute
  '/editor': typeof ProtectedEditorRoute
  '/join/$token': typeof JoinTokenRoute
  '/': typeof ProtectedIndexRoute
  '/lesson/$id': typeof ProtectedLessonIdRoute
  '/teacher/subscribe': typeof ProtectedTeacherSubscribeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/collab': typeof ProtectedCollabRoute
  '/editor': typeof ProtectedEditorRoute
  '/join/$token': typeof JoinTokenRoute
  '/': typeof ProtectedIndexRoute
  '/lesson/$id': typeof ProtectedLessonIdRoute
  '/teacher/subscribe': typeof ProtectedTeacherSubscribeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_protected/collab': typeof ProtectedCollabRoute
  '/_protected/editor': typeof ProtectedEditorRoute
  '/join/$token': typeof JoinTokenRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/lesson/$id': typeof ProtectedLessonIdRoute
  '/_protected/teacher/subscribe': typeof ProtectedTeacherSubscribeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/signup'
    | '/collab'
    | '/editor'
    | '/join/$token'
    | '/'
    | '/lesson/$id'
    | '/teacher/subscribe'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/collab'
    | '/editor'
    | '/join/$token'
    | '/'
    | '/lesson/$id'
    | '/teacher/subscribe'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_protected/collab'
    | '/_protected/editor'
    | '/join/$token'
    | '/_protected/'
    | '/_protected/lesson/$id'
    | '/_protected/teacher/subscribe'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  JoinTokenRoute: typeof JoinTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/editor': {
      id: '/_protected/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof ProtectedEditorRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/collab': {
      id: '/_protected/collab'
      path: '/collab'
      fullPath: '/collab'
      preLoaderRoute: typeof ProtectedCollabRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/teacher/subscribe': {
      id: '/_protected/teacher/subscribe'
      path: '/teacher/subscribe'
      fullPath: '/teacher/subscribe'
      preLoaderRoute: typeof ProtectedTeacherSubscribeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/lesson/$id': {
      id: '/_protected/lesson/$id'
      path: '/lesson/$id'
      fullPath: '/lesson/$id'
      preLoaderRoute: typeof ProtectedLessonIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedCollabRoute: typeof ProtectedCollabRoute
  ProtectedEditorRoute: typeof ProtectedEditorRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedLessonIdRoute: typeof ProtectedLessonIdRoute
  ProtectedTeacherSubscribeRoute: typeof ProtectedTeacherSubscribeRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedCollabRoute: ProtectedCollabRoute,
  ProtectedEditorRoute: ProtectedEditorRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedLessonIdRoute: ProtectedLessonIdRoute,
  ProtectedTeacherSubscribeRoute: ProtectedTeacherSubscribeRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  JoinTokenRoute: JoinTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
