/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedAppRouteRouteImport } from './routes/_protected/_app/route'
import { Route as ProtectedAppIndexRouteImport } from './routes/_protected/_app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedAppLibraryRouteImport } from './routes/_protected/_app/library'
import { Route as ProtectedAppSpacesIdRouteImport } from './routes/_protected/_app/spaces.$id'
import { Route as ProtectedSpacesIdLessonNewRouteImport } from './routes/_protected/spaces.$id_.lesson.new'
import { Route as ProtectedSpacesIdLessonLessonIdRouteImport } from './routes/_protected/spaces.$id_.lesson.$lessonId'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedAppRouteRoute = ProtectedAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAppIndexRoute = ProtectedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAppLibraryRoute = ProtectedAppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ProtectedAppRouteRoute,
} as any)
const ProtectedAppSpacesIdRoute = ProtectedAppSpacesIdRouteImport.update({
  id: '/spaces/$id',
  path: '/spaces/$id',
  getParentRoute: () => ProtectedAppRouteRoute,
} as any)
const ProtectedSpacesIdLessonNewRoute =
  ProtectedSpacesIdLessonNewRouteImport.update({
    id: '/spaces/$id_/lesson/new',
    path: '/spaces/$id/lesson/new',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSpacesIdLessonLessonIdRoute =
  ProtectedSpacesIdLessonLessonIdRouteImport.update({
    id: '/spaces/$id_/lesson/$lessonId',
    path: '/spaces/$id/lesson/$lessonId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/library': typeof ProtectedAppLibraryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof ProtectedAppIndexRoute
  '/spaces/$id': typeof ProtectedAppSpacesIdRoute
  '/spaces/$id/lesson/$lessonId': typeof ProtectedSpacesIdLessonLessonIdRoute
  '/spaces/$id/lesson/new': typeof ProtectedSpacesIdLessonNewRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/library': typeof ProtectedAppLibraryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof ProtectedAppIndexRoute
  '/spaces/$id': typeof ProtectedAppSpacesIdRoute
  '/spaces/$id/lesson/$lessonId': typeof ProtectedSpacesIdLessonLessonIdRoute
  '/spaces/$id/lesson/new': typeof ProtectedSpacesIdLessonNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/_app': typeof ProtectedAppRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_protected/_app/library': typeof ProtectedAppLibraryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/_app/': typeof ProtectedAppIndexRoute
  '/_protected/_app/spaces/$id': typeof ProtectedAppSpacesIdRoute
  '/_protected/spaces/$id_/lesson/$lessonId': typeof ProtectedSpacesIdLessonLessonIdRoute
  '/_protected/spaces/$id_/lesson/new': typeof ProtectedSpacesIdLessonNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/signup'
    | '/library'
    | '/api/auth/$'
    | '/'
    | '/spaces/$id'
    | '/spaces/$id/lesson/$lessonId'
    | '/spaces/$id/lesson/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/library'
    | '/api/auth/$'
    | '/'
    | '/spaces/$id'
    | '/spaces/$id/lesson/$lessonId'
    | '/spaces/$id/lesson/new'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_protected/_app'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_protected/_app/library'
    | '/api/auth/$'
    | '/_protected/_app/'
    | '/_protected/_app/spaces/$id'
    | '/_protected/spaces/$id_/lesson/$lessonId'
    | '/_protected/spaces/$id_/lesson/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/_app': {
      id: '/_protected/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedAppRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/_app/': {
      id: '/_protected/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedAppIndexRouteImport
      parentRoute: typeof ProtectedAppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_app/library': {
      id: '/_protected/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof ProtectedAppLibraryRouteImport
      parentRoute: typeof ProtectedAppRouteRoute
    }
    '/_protected/_app/spaces/$id': {
      id: '/_protected/_app/spaces/$id'
      path: '/spaces/$id'
      fullPath: '/spaces/$id'
      preLoaderRoute: typeof ProtectedAppSpacesIdRouteImport
      parentRoute: typeof ProtectedAppRouteRoute
    }
    '/_protected/spaces/$id_/lesson/new': {
      id: '/_protected/spaces/$id_/lesson/new'
      path: '/spaces/$id/lesson/new'
      fullPath: '/spaces/$id/lesson/new'
      preLoaderRoute: typeof ProtectedSpacesIdLessonNewRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/spaces/$id_/lesson/$lessonId': {
      id: '/_protected/spaces/$id_/lesson/$lessonId'
      path: '/spaces/$id/lesson/$lessonId'
      fullPath: '/spaces/$id/lesson/$lessonId'
      preLoaderRoute: typeof ProtectedSpacesIdLessonLessonIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedAppRouteRouteChildren {
  ProtectedAppLibraryRoute: typeof ProtectedAppLibraryRoute
  ProtectedAppIndexRoute: typeof ProtectedAppIndexRoute
  ProtectedAppSpacesIdRoute: typeof ProtectedAppSpacesIdRoute
}

const ProtectedAppRouteRouteChildren: ProtectedAppRouteRouteChildren = {
  ProtectedAppLibraryRoute: ProtectedAppLibraryRoute,
  ProtectedAppIndexRoute: ProtectedAppIndexRoute,
  ProtectedAppSpacesIdRoute: ProtectedAppSpacesIdRoute,
}

const ProtectedAppRouteRouteWithChildren =
  ProtectedAppRouteRoute._addFileChildren(ProtectedAppRouteRouteChildren)

interface ProtectedRouteRouteChildren {
  ProtectedAppRouteRoute: typeof ProtectedAppRouteRouteWithChildren
  ProtectedSpacesIdLessonLessonIdRoute: typeof ProtectedSpacesIdLessonLessonIdRoute
  ProtectedSpacesIdLessonNewRoute: typeof ProtectedSpacesIdLessonNewRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAppRouteRoute: ProtectedAppRouteRouteWithChildren,
  ProtectedSpacesIdLessonLessonIdRoute: ProtectedSpacesIdLessonLessonIdRoute,
  ProtectedSpacesIdLessonNewRoute: ProtectedSpacesIdLessonNewRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
