/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedLibraryRouteImport } from './routes/_protected/library'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedSpacesIdRouteImport } from './routes/_protected/spaces.$id'
import { Route as ProtectedDocumentIdRouteImport } from './routes/_protected/document.$id'
import { Route as ProtectedSpacesIdNewLessonRouteImport } from './routes/_protected/spaces.$id.new-lesson'
import { Route as ProtectedSpacesIdLessonLessonIdRouteImport } from './routes/_protected/spaces.$id.lesson.$lessonId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedLibraryRoute = ProtectedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSpacesIdRoute = ProtectedSpacesIdRouteImport.update({
  id: '/spaces/$id',
  path: '/spaces/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDocumentIdRoute = ProtectedDocumentIdRouteImport.update({
  id: '/document/$id',
  path: '/document/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSpacesIdNewLessonRoute =
  ProtectedSpacesIdNewLessonRouteImport.update({
    id: '/new-lesson',
    path: '/new-lesson',
    getParentRoute: () => ProtectedSpacesIdRoute,
  } as any)
const ProtectedSpacesIdLessonLessonIdRoute =
  ProtectedSpacesIdLessonLessonIdRouteImport.update({
    id: '/lesson/$lessonId',
    path: '/lesson/$lessonId',
    getParentRoute: () => ProtectedSpacesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/library': typeof ProtectedLibraryRoute
  '/': typeof ProtectedIndexRoute
  '/document/$id': typeof ProtectedDocumentIdRoute
  '/spaces/$id': typeof ProtectedSpacesIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/spaces/$id/new-lesson': typeof ProtectedSpacesIdNewLessonRoute
  '/spaces/$id/lesson/$lessonId': typeof ProtectedSpacesIdLessonLessonIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/library': typeof ProtectedLibraryRoute
  '/': typeof ProtectedIndexRoute
  '/document/$id': typeof ProtectedDocumentIdRoute
  '/spaces/$id': typeof ProtectedSpacesIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/spaces/$id/new-lesson': typeof ProtectedSpacesIdNewLessonRoute
  '/spaces/$id/lesson/$lessonId': typeof ProtectedSpacesIdLessonLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_protected/library': typeof ProtectedLibraryRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/document/$id': typeof ProtectedDocumentIdRoute
  '/_protected/spaces/$id': typeof ProtectedSpacesIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/spaces/$id/new-lesson': typeof ProtectedSpacesIdNewLessonRoute
  '/_protected/spaces/$id/lesson/$lessonId': typeof ProtectedSpacesIdLessonLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/signup'
    | '/library'
    | '/'
    | '/document/$id'
    | '/spaces/$id'
    | '/api/auth/$'
    | '/spaces/$id/new-lesson'
    | '/spaces/$id/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/library'
    | '/'
    | '/document/$id'
    | '/spaces/$id'
    | '/api/auth/$'
    | '/spaces/$id/new-lesson'
    | '/spaces/$id/lesson/$lessonId'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_protected/library'
    | '/_protected/'
    | '/_protected/document/$id'
    | '/_protected/spaces/$id'
    | '/api/auth/$'
    | '/_protected/spaces/$id/new-lesson'
    | '/_protected/spaces/$id/lesson/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/library': {
      id: '/_protected/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof ProtectedLibraryRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/spaces/$id': {
      id: '/_protected/spaces/$id'
      path: '/spaces/$id'
      fullPath: '/spaces/$id'
      preLoaderRoute: typeof ProtectedSpacesIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/document/$id': {
      id: '/_protected/document/$id'
      path: '/document/$id'
      fullPath: '/document/$id'
      preLoaderRoute: typeof ProtectedDocumentIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/spaces/$id/new-lesson': {
      id: '/_protected/spaces/$id/new-lesson'
      path: '/new-lesson'
      fullPath: '/spaces/$id/new-lesson'
      preLoaderRoute: typeof ProtectedSpacesIdNewLessonRouteImport
      parentRoute: typeof ProtectedSpacesIdRoute
    }
    '/_protected/spaces/$id/lesson/$lessonId': {
      id: '/_protected/spaces/$id/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/spaces/$id/lesson/$lessonId'
      preLoaderRoute: typeof ProtectedSpacesIdLessonLessonIdRouteImport
      parentRoute: typeof ProtectedSpacesIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedSpacesIdRouteChildren {
  ProtectedSpacesIdNewLessonRoute: typeof ProtectedSpacesIdNewLessonRoute
  ProtectedSpacesIdLessonLessonIdRoute: typeof ProtectedSpacesIdLessonLessonIdRoute
}

const ProtectedSpacesIdRouteChildren: ProtectedSpacesIdRouteChildren = {
  ProtectedSpacesIdNewLessonRoute: ProtectedSpacesIdNewLessonRoute,
  ProtectedSpacesIdLessonLessonIdRoute: ProtectedSpacesIdLessonLessonIdRoute,
}

const ProtectedSpacesIdRouteWithChildren =
  ProtectedSpacesIdRoute._addFileChildren(ProtectedSpacesIdRouteChildren)

interface ProtectedRouteChildren {
  ProtectedLibraryRoute: typeof ProtectedLibraryRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedDocumentIdRoute: typeof ProtectedDocumentIdRoute
  ProtectedSpacesIdRoute: typeof ProtectedSpacesIdRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedLibraryRoute: ProtectedLibraryRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedDocumentIdRoute: ProtectedDocumentIdRoute,
  ProtectedSpacesIdRoute: ProtectedSpacesIdRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
